
query PageBySlug($slug: String!) {
  pages(filters: { slug: { eq: $slug } }, pagination: {
     limit: 1
  }) {
    contentBlocks {
      ... on ComponentContentBlocksHero {
        __typename
        id
        title
        image {
          documentId
          name
          alternativeText
          caption
          width
          height
          formats
          hash
          ext
          mime
          size
          url
          previewUrl
          provider
          provider_metadata
        }
      }
      ... on ComponentContentBlocksText {
        __typename
        textText: text
        id
      }
      ... on ComponentContentBlocksRiver {
        __typename
        id
        imageLeft
        riverText: text
        riverImage: image {
          documentId
          name
          alternativeText
          caption
          width
          height
          formats
          hash
          ext
          mime
          size
          url
          previewUrl
          provider
          provider_metadata
        }
      }
      ... on Error {
        __typename
        code
        message
      }
    }
  }
}
